import random
from town_names import generate_town_name


class City:
    def __init__(self, generationType, x, y):
        self.name = generate_town_name()
        self.population = random.randint(5000, 50000)
        self.position = [x, y]  # position on the map
        self.station = None

        if generationType == 1:  # If randomly generated by the game
            print(
                f"A new city with the name {self.name} has been founded! It has a population of {self.population} people"
            )
        elif generationType == 2:  # If created by the player
            print(
                f"A new city with the name {self.name} has succesfully been created! It has a population of {self.population} people"
            )

    def grow_city(self):
        self.population += random.randint(1000, 10000)
        print(
            f"The city {self.name} has grown! It now has a population of {self.population} people"
        )

    def spawn_passangers(self, stations):
        currentStation = stations[self.station]
        if stations[self.station]["amountOfRoutes"] > 0:
            waitingPassangers = currentStation["waitingPassangers"] + (
                self.population / 10) / (1 + currentStation["waitingPassangers"])
            currentStation["waitingPassangers"] = int(waitingPassangers)


def cities_menu(cities):
    while True:
        print("-" * 83)
        print(f"|{'city name':<20} | {'population':>20} | {'does the city has a station?':>35}|")
        print("-" * 83)
        for city in cities:
            if city.station:
                hasStation = "This city has a station"
            else:
                hasStation = "This city does not have a station"
            print(f"|{city.name:<20} | {str(city.population):>20} | {hasStation:<35}|")
        print("-" * 83)
        print("Type 'q' to go back")
        choice = input("")
        if choice.lower() == "q":
            break


def city_logic(cities):
    if random.randint(0, 500) == 1:
        cities.append(City(1, random.randint(0, 100), random.randint(0, 100)))  # TODO: add actual position logic
    for city in cities:
        # Random growth
        # TODO: add some logic to this so cities dont actually randomly grow. Let them grow on a condition.
        if random.randint(0, 50) == 1:
            city.grow_city()
        # Spawn passengers at the station
        if city.station:
            city.station.spawn_passengers()
